### ISSUE TITLE
Can't fetch anything from MetroLyrics

### ISSUE THREAD

**Issue by jlongrc** [javichito/Lyricfy#7]
I think MetroLyrics has just changed too much since this was last updated. I ran 20 songs through it, all of which were found on Wikia, but could not be found on ML.

**Comment by javichito** [comment]
I have done a push that seems to fix the problem, please try it again and confirm before i close this issue.

**Comment by jlongrc** [comment]
Yes, this is working. I appreciate the quick response, especially on a project that has been idle for a while. You helped this Ruby beginner quite a bit.

**Comment by javichito** [comment]
Glad to hear that.
